icon generator only remove fill for nodes in Main
mycolorway/tao_on_rails pull request #13
Opened 2017-03-22 09:54 UTC by louis-she

2017-03-22 12:39 UTC, farthinker requested changes

2017-03-22 12:39 UTC, farthinker commented on tao_on_rails.gemspec
> +  spec.add_dependency "nokogiri", '~> 1.7.1'
这个应该是dev dependency

2017-03-22 15:20 UTC, louis-she commented
@farthinker 改好了

2017-03-23 07:30 UTC, farthinker approved these changes

2017-03-23 07:30 UTC, merged